#!/bin/bash

# Script to launch audio servers for music-making.

case $1 in

  start )
    pasuspender -- \
        jackd -d alsa --device hw:0 --rate 44100 --period 128 \
            &>/tmp/jackd.out &

    # Start fluidsynth
    fluidsynth --server --no-shell --audio-driver=jack \
        --connect-jack-outputs --reverb=0 --chorus=0 --gain=0.8  \
        ~/.soundfonts/PianoGrand.sf2 \
        &>/tmp/fluidsynth.out &

    sleep 2

    if pgrep jackd && pgrep fluidsynth
    then
        aconnect 24 128
      echo Audio servers running.
    else
      echo There was a problem starting the audio servers.
    fi

    ;;

  stop )
    killall fluidsynth
    killall jackd
    echo Audio servers stopped.
    ;;

  * )
    echo Please specify start or stop...
    ;;
esac
