#!/bin/bash
docker $1 db_mysql
sleep 2
docker $1 db_redis
sleep 2
docker $1 rabbitmq
sleep 2
docker $1 hal
sleep 2
docker $1 api
sleep 2
docker $1 hostbill
sleep 2
docker $1 hapi
sleep 2
docker $1 mapp
sleep 2
docker $1 front
sleep 2
docker $1 gopanel
sleep 2
docker $1 apiproxy
sleep 2
docker $1 controlpanel
sleep 2
docker $1 router
sleep 2
docker $1 executor
sleep 2
docker $1 kudeiro
