#!/bin/bash
HOSTS="gremiocazadores.es gremiocazadores.com www.gremiocazadores.es www.gremiocazadores.com"
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
while true
do
    clear;
    for myHost in $HOSTS
    do
      if ! ping -c1 $myHost &>/dev/null; then
         printf "${YELLOW}${myHost} ${RED}False\n"
      else
         printf "${YELLOW}${myHost} ${GREEN}True\n"
      fi
    done
    sleep 60;
done
